In [1]:
import numpy as np
import pickle
from scipy import signal
from scipy.spatial.distance import euclidean
from fastdtw import fastdtw
import copy
import matplotlib.pyplot as plt
from numpy import cos, sin, pi, absolute, arange
from scipy.signal import kaiserord, lfilter, firwin, freqz
from pylab import figure, clf, plot, xlabel, ylabel, xlim, ylim, title, grid, axes, show
import numpy as np
from scipy.fftpack import fft, ifft
import scipy.signal as signal
import numpy as np
import pickle
from scipy import signal
from scipy.spatial.distance import euclidean
from fastdtw import fastdtw
import copy
import matplotlib.pyplot as plt
%matplotlib inline
import pytz # new import
import datetime
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn import preprocessing
from sklearn import utils
import copy
from copy import deepcopy
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import pandas as pd
from fun2 import *
from sklearn import linear_model
from sklearn.neural_network import MLPClassifier

In [2]:
path = '0820_data/minute_data_0820'
names = ['HRV15-002', 'HRV15-003', 'HRV15-004', 'HRV15-005', 'HRV15-006', 'HRV15-007', 'HRV15-008', 'HRV15-009', 'HRV15-011', 'HRV15-012', 'HRV15-013',  'HRV15-017', 'HRV15-018', 'HRV15-019', 'HRV15-020', 'HRV15-021', 'HRV15-022', 'HRV15-023', 'HRV15-024']
label = pickle.load(open("labels.pkl", "rb" )).tolist()
#df_groupby_minute_total = read_data(path)

In [3]:
start_train,end_train = 15, 17
start_test,end_test = 17, 18
start_hour,end_hour = '09','08'
n = 0

result0 = result_time_shift(path,start_train,end_train,start_test,end_test,start_hour,end_hour,names,label,n)


In [4]:
result0

(0.5555555555555556,
 1e-08,
 ['HRV15-003',
  'HRV15-006',
  'HRV15-007',
  'HRV15-008',
  'HRV15-013',
  'HRV15-021',
  'HRV15-022',
  'HRV15-024'],
 [],
 array([[  12.34693793,    7.7526988 ,   10.82924493],
        [  14.54666725,   24.1704159 ,   12.93539849],
        [  16.42891026,    7.61370106,   17.04701645],
        [  15.75967664,   12.11026296,   24.63404996],
        [  13.08445108,   17.23217943,   11.76737894],
        [  16.93325992,   20.37835524,    9.12497852],
        [  26.93995938,    8.63336056,   10.14987239],
        [  19.46206101,   86.87868221,   13.32718787],
        [  19.75808075,   21.74895693,   11.56454669],
        [  16.64344197,   17.02737865,    8.76860666],
        [  24.33694203,   15.49369604,   22.55825022],
        [  37.8465362 ,   11.35415448,   13.52741969],
        [  13.89588867,   16.85368869,   15.51982041],
        [  24.66958479,   46.27673157,  199.72551338],
        [  19.05249723,   12.38982448,   14.62428537],
        [  11.232893

In [5]:
start_train,end_train = 15, 17
start_test,end_test = 17, 18
start_hour,end_hour = '10','09'
n = 1

result1 = result_time_shift(path,start_train,end_train,start_test,end_test,start_hour,end_hour,names,label,n)



In [6]:
result1

(0.5555555555555556,
 1e-08,
 ['HRV15-003',
  'HRV15-006',
  'HRV15-007',
  'HRV15-008',
  'HRV15-013',
  'HRV15-021',
  'HRV15-022',
  'HRV15-024'],
 [],
 array([[  14.00103007,   10.63517728,    9.3785986 ],
        [  20.48555546,   28.25773345,   20.96290916],
        [  22.09056756,    7.15171628,   13.44056938],
        [  16.94825622,   12.02381988,   21.16041213],
        [  13.21422894,   11.52145969,   11.96998368],
        [  21.08990472,   16.40798581,   10.42024063],
        [  29.5526355 ,   24.73426828,   10.39274167],
        [  24.96749948,   38.27560306,   16.68516187],
        [  15.09438465,   21.18771643,   15.63790018],
        [  22.47656256,   17.41564394,    8.84268832],
        [  16.87513665,   18.0105764 ,   18.04165991],
        [  11.57252813,   21.69821281,   10.47507708],
        [  16.57410283,   20.60657042,   14.7203485 ],
        [  21.53421675,   25.25249628,  199.72551338],
        [  13.65074754,   13.02681829,   12.54477484],
        [  16.687306

In [7]:
start_train,end_train = 15, 17
start_test,end_test = 17, 18
start_hour,end_hour = '11','10'
n = 2

result2 = result_time_shift(path,start_train,end_train,start_test,end_test,start_hour,end_hour,names,label,n)




In [8]:
result2

(0.5555555555555556,
 1,
 ['HRV15-003', 'HRV15-006', 'HRV15-008', 'HRV15-013', 'HRV15-024'],
 ['HRV15-009', 'HRV15-012', 'HRV15-023'],
 array([[  14.20656495,   12.40833067,   10.9293125 ],
        [  22.40498421,   22.0434356 ,   19.81595361],
        [  15.73950856,    7.51635734,   13.78069707],
        [  24.69023644,   11.60796986,   24.96241779],
        [  13.67353197,   14.40883235,   14.25104859],
        [  21.86007367,   20.11346088,    8.82244446],
        [  27.36535873,  302.41870853,    8.81834615],
        [  20.51796152,   38.57300582,   15.74043805],
        [  15.45669713,   29.00754804,   14.88669661],
        [  23.76386883,   19.64545242,   15.94989092],
        [  25.63211647,   38.47179452,   21.85855899],
        [  13.39792765,   20.09605435,   11.97670686],
        [  16.74123749,   19.1071004 ,   13.02706381],
        [  17.89499284,   23.16615931,  199.72551338],
        [  20.9945634 ,   11.64246082,   12.84566521],
        [  17.57465404,   10.28106506,  

In [9]:
start_train,end_train = 15, 17
start_test,end_test = 17, 18
start_hour,end_hour = '12','11'
n = 3

result3 = result_time_shift(path,start_train,end_train,start_test,end_test,start_hour,end_hour,names,label,n)





In [10]:
result3

(0.6111111111111112,
 0.01,
 ['HRV15-003', 'HRV15-006', 'HRV15-007', 'HRV15-021', 'HRV15-024'],
 ['HRV15-009', 'HRV15-012'],
 array([[  16.48183016,    8.74713155,   10.54338114],
        [  21.00204345,   23.5029484 ,   20.32118829],
        [  14.15179937,   25.03042025,   14.48949232],
        [  15.40671454,   19.76093489,   34.28024966],
        [  15.56021849,   10.83643027,   14.62286915],
        [  18.11064413,   30.18857113,   10.62414272],
        [  14.36062337,  152.9245971 ,    9.81770075],
        [  18.97255824,   44.85388182,   12.65335748],
        [  15.82678354,   20.91250895,   14.94367257],
        [  18.93382475,   34.21987775,   14.91613736],
        [  19.55526508,   73.41673512,   22.56904565],
        [  17.98012263,   21.42165359,   10.43943933],
        [  16.11313203,   19.95293442,   17.18229262],
        [  16.43615739,   21.01764438,  199.72551338],
        [  13.01503634,    9.96571692,   12.15197507],
        [  14.12369454,   44.48947349,   13.949816

In [ ]:
A = np.zeros((18,3))

In [ ]:
A[3:8] = [1,1,1]

In [ ]:
b= np.zeros(19)
b[3:8] = 1
b = b.tolist()

In [ ]:
len(b)

In [ ]:
len(label)

In [ ]:
pick_best_fn_fp(A,b,names)